### ISSUE TITLE
does this work with Jquery 2.1?

### ISSUE THREAD

**Issue by ewassef** [zuk/jquery.inview#11]
$.cache seems to always be null and no events fire. is it not compatible anymore?

Thanks

**Comment by tomaszrondio** [comment]
it is pretty easy. 

around line 50
remove: 
         $.each($._data, function() {
             if (this.events && this.events.inview) {
                 elems.push(this.handle.elem);
             }
         });

and replace:
$(elems).each()...
with:
$('.inview').each()...

it requires that every element that should be watched has to have inview class.

**Comment by magixx** [comment]
Still broken for me on 2.1.1 and latest. See http://jsbin.com/kaburov/edit?html,css,js,console,output
