### ISSUE TITLE
CC-BY-NC-SA-2.0 or MIT license ?

### ISSUE THREAD

**Issue by maruilian11** [zuk/jquery.inview#22]
hi, we want to add your lib on https://cdnjs.com, i saw CC-BY-NC-SA-2.0 in your [LICENSE](https://github.com/zuk/jquery.inview/blob/master/LICENSE) but MIT in your [bower.json](https://github.com/zuk/jquery.inview/blob/master/bower.json#L19), just want to confirm this with you.
thank you!

https://github.com/cdnjs/cdnjs/issues/5620

**Comment by zuk** [comment]
The bower.json was added by another contributor, but the original code was based off a blog post by Remy Sharp (https://remysharp.com/2009/01/26/element-in-view-event-plugin). At the time when I copied the code onto GitHub, I believe it was licensed as CC, but it looks like the code portion is now under MIT. I'll go ahead and change the LICENSE file to match.

**Comment by maruilian11** [comment]
thank you :+1:
